"""Numeric Constants for use in IO elements.
See also: Documentation/Specifications"""

SCREEN_WIDTHS = 1920
SCREEN_HEIGHT = 1080

ACTIONS_ROW_CENTER_HEIGHT = 90
PEOPLE_ROW_TOP = 180
PEOPLE_ROW_CENTER_HEIGHT = 430
HAND_ROW_CENTER_HEIGHT = 880

PEOPLE_ROW_CENTER_WIDTH = 960
GAP_PEOPLE = 40
PERSON_WIDTHS = 200
STANCE_SPACE_WIDTHS = 250
